spring.application.name=love-app-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/love_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trendfeett@gmail.com
spring.mail.password=lhautqtcvduymjmj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

mercadopago.token=APP_USR-7339802827319701-040609-4c66b7a949a27b18be6fbaef1be2cac1-3315716311